#!/bin/bash
# Copyright 2010,2012 Google Inc.
#
#   This Source Code Form is subject to the terms of the Mozilla Public
#   License, v. 2.0. If a copy of the MPL was not distributed with this
#   file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Script to launch crack under valgrind.

LIBS=$(dirname $0)/.libs
LD_LIBRARY_PATH=$LIBS valgrind $LIBS/crack "$@"
